export const tokens = {
  color: {
    primary: 'var(--phi-color-primary)',
    primaryHover: 'var(--phi-color-primary-hover)',
    primaryLight: 'var(--phi-color-primary-light)',
    secondary: 'var(--phi-color-secondary)',
    secondaryHover: 'var(--phi-color-secondary-hover)',
    success: 'var(--phi-color-success)',
    successLight: 'var(--phi-color-success-light)',
    warning: 'var(--phi-color-warning)',
    warningLight: 'var(--phi-color-warning-light)',
    error: 'var(--phi-color-error)',
    errorHover: 'var(--phi-color-error-hover)',
    errorLight: 'var(--phi-color-error-light)',
    info: 'var(--phi-color-info)',
    infoHover: 'var(--phi-color-info-hover)',
    infoLight: 'var(--phi-color-info-light)',
    background: 'var(--phi-color-background)',
    backgroundSecondary: 'var(--phi-color-background-secondary)',
    backgroundCard: 'var(--phi-color-background-card)',
    textPrimary: 'var(--phi-color-text-primary)',
    textSecondary: 'var(--phi-color-text-secondary)',
    textInverse: 'var(--phi-color-text-inverse)',
    border: 'var(--phi-color-border)',
  },
  shadow: {
    sm: 'var(--phi-shadow-sm)',
    md: 'var(--phi-shadow-md)',
    lg: 'var(--phi-shadow-lg)',
  },
  radius: {
    sm: 'var(--phi-radius-sm)',
    md: 'var(--phi-radius-md)',
    lg: 'var(--phi-radius-lg)',
    xl: 'var(--phi-radius-xl)',
    full: 'var(--phi-radius-full)',
  },
  spacing: {
    1: 'var(--phi-space-1)',
    2: 'var(--phi-space-2)',
    3: 'var(--phi-space-3)',
    4: 'var(--phi-space-4)',
    5: 'var(--phi-space-5)',
    6: 'var(--phi-space-6)',
  },
  layout: {
    sidebarMargin: 'var(--phi-layout-sidebar-margin)',
    headerHeight: 'var(--phi-layout-header-height)',
    contentPadding: 'var(--phi-layout-content-padding)',
    headerGlow: 'var(--phi-layout-header-glow)',
    sidebarCollapsedWidth: 'var(--phi-sidebar-collapsed-width)',
    sidebarExpandedWidth: 'var(--phi-sidebar-expanded-width)',
    sidebarCollapsedSpacer: 'var(--phi-sidebar-collapsed-spacer)',
    sidebarExpandedSpacer: 'var(--phi-sidebar-expanded-spacer)',
    sidebarHeaderHeight: 'var(--phi-sidebar-header-height)',
  },
  font: {
    family: 'var(--phi-font-family)',
    heading: 'var(--phi-font-heading)',
    mono: 'var(--phi-font-mono)',
    siteActive: 'var(--phi-font-site-active)',
    sizeXs: 'var(--phi-font-size-xs)',
    sizeSm: 'var(--phi-font-size-sm)',
    sizeBase: 'var(--phi-font-size-base)',
    sizeLg: 'var(--phi-font-size-lg)',
    sizeXl: 'var(--phi-font-size-xl)',
    sizeXxl: 'var(--phi-font-size-xxl)',
    weightNormal: 'var(--phi-font-weight-normal)',
    weightMedium: 'var(--phi-font-weight-medium)',
    weightSemibold: 'var(--phi-font-weight-semibold)',
    weightBold: 'var(--phi-font-weight-bold)',
  },
  motion: {
    fast: 'var(--phi-transition-fast)',
    normal: 'var(--phi-transition-normal)',
  },
} as const;
